name: 'CI workflow'

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Lint, Format and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (no fix)
        run: npm run lint

      - name: formating
        run: npx prettier --write .

      - name: Check Format (no fix)
        run: npm run format:check

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run tests
        run: npm test
